# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Generate test statistic from bootstrap samples
#' 
#' @description This function simulates the DGP under the null hypothesis and computes the test statistic for each sample
#' 
#' @return vector of simulated test statistics
#' 
#' @export
bootNullDist_ex <- function(param_null, std, n, B) {
    .Call(`_bootBtest_bootNullDist_ex`, param_null, std, n, B)
}

